spring:
  r2dbc:
    url: r2dbc:h2:file:///./data/meetme-db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;AUTO_RECONNECT=TRUE
    username: sa
    password:

logging:
  level:
    com.meetme.meetmeserver: TRACE
    org.springframework.data.r2dbc: TRACE